### ISSUE TITLE
User cannot navigate to previous directory from the one they started 

### ISSUE THREAD

**Issue by souvikinator** [souvikinator/lsx#1]
As of now if user starts from `~/abc` then they can navigate forward in this path (`~/abc/def/....`), they can also navigate backward but only till point `~/abc` after which user cannot go to the previous path of `~/abc`.

**Comment by nagy135** [comment]
I dont know if this is intended but I still cant go back using keybinds, only using `..`. It makes it inconsistent in my opinion

**Comment by souvikinator** [comment]
It is intentional. You can navigate to previous directory using `..`. 
The key bindings are only for navigating through the list and not directories.
