### ISSUE TITLE
zsh: lsx: function definition file not found

### ISSUE THREAD

**Issue by m-bob** [souvikinator/lsx#23]
Hi!

I'm on a MacBook Pro, running zsh on Catalina.

Typing lsx gives 

zsh: lsx: function definition file not found

I'm not a go user, so there might be issues with how it's set up on my machine.

Thanks!

**Comment by souvikinator** [comment]
Hey there, I hope you followed the installation instructions. 

Can you make sure if the following path exists in your machine?
`~/.oh-my-zsh/functions`
and if exists then is there any file named `lsx` in there?

**Comment by m-bob** [comment]
Thanks for the fast reply! I'm using .zsh, but not .oh-my-zsh. So, no
.oh-my-zsh folder on my machine.

I'll try installing it.

(BTW, I followed the instructions on the github site. The installation
procedure completed without alerting me to anything amiss.)

Again, thanks!

Murray

**Comment by m-bob** [comment]
Ok, I just installed oh-my-zsh, and re-installed lsx.

Several consequences:

lsx still doesn't work. Now I see the messages:

lsx:17: command not found: ls-x
cat: /Users/murray/.config/lsx/lsx.tmp: No such file or directory

But also, I have lost the powerlevel10k prompt I worked hard to create. Not
your fault, and I may have a backup. But you might want to document the
requirement for oh-my-zsh.

I'm going to revert to my previous (oh-my-zsh-less) configuration.

Again, thanks!

Murray

**Comment by souvikinator** [comment]
oh! I'm sorry about that. I'll add support for `zsh` shell. Thanks for reporting.

**Comment by m-bob** [comment]
No problem, thanks!

**Comment by markring40-git** [comment]
Hi,
I'm running Arch Linux 5.15.12-arch1-1.  My shell is zsh 5.8.  I followed the installation instructions.  When I enter lsx -a into the command line I get the following error message:
lsx:17: command not found: ls-x

**Comment by souvikinator** [comment]
@markring40-git hey! Can you tell me what is the output of `echo $GOPATH` in your shell?

**Comment by markring40-git** [comment]
![pic-full-211231-1236-57](https://user-images.githubusercontent.com/63985747/147835798-784998f2-ad8c-413c-b10d-8ecf07dd0040.png)

**Comment by souvikinator** [comment]
wow that's weird. Can you check if there is `ls-x` executable in your `$GOPATH` (`/home/mark/.local/share/go` in your case) ?

**Comment by markring40-git** [comment]
I found ls-x in: /home/mark/.local/share/go/bin
I added that to my path to my $GOPATH, but no change.

**Comment by souvikinator** [comment]
That's even weird, if it is in the path then it should work.
What does `which ls-x` returns? Did you add export path in your shell specific file?

**Comment by markring40-git** [comment]
> which ls-x 
returns: 
> ls-x not found.  
No I have not added it.  I'll try that.  Thank you for your help.

**Comment by souvikinator** [comment]
so ls-x is not in your path. Let me know if you face any issues with that.

**Comment by markring40-git** [comment]
Moved ls-x into the appropriate location. It now works like a charm.  Thanks again for your help and your patience!

**Comment by souvikinator** [comment]
That's awesome! Thanks for using :))

**Comment by arilebedey** [comment]
I am having the same issue with all the I am using arch and zsh.
`$ lsx` yields "lsx:17: command not found: ls-x"
my echo $GOPATH is ~/go. I do have ls-x in ~/go/bin
What should I try..?
Thanks..

**Comment by souvikinator** [comment]
you need to add `$GOPATH/bin` to your path like so,
Add the following lines at the end of your shell-specific file (`.zshrc` or `.bashrc` ....)

```bash
export PATH=$PATH:$GOPATH/bin
```
let me know if you face any issue.

**Comment by arilebedey** [comment]
It worked..!! Thanks for the lesson..and the program..! 😃
