### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by Hebgbs** [souvikinator/lsx#27]
Please rename this project. It is in conflict with Suckless `lsx` which lists executables.

**Comment by souvikinator** [comment]
Sorry, that is not possible. For your use situation, you can simply change the name as per your preference over here and run the installation script. 
https://github.com/souvikinator/lsx/blob/00a9ecca00032b679592009268c7c9f79a172ee2/script/lsx.sh#L1

Let me know if you face any issues while doing that.
