### ISSUE TITLE
zsh: command not found: ls-x

### ISSUE THREAD

**Issue by SuddenPineapple** [souvikinator/lsx#29]
After struggling with the $GOPATH thing I also added the source at the end of my .zshrc and now when I try to run it I get the aformentioned error.

**Comment by souvikinator** [comment]
what does `echo $GOPATH` return?

**Comment by SuddenPineapple** [comment]
I forgot to add /go/bin to $PATH. PICNIC

**Comment by souvikinator** [comment]
is it working now?

**Comment by SuddenPineapple** [comment]
Yes

**Comment by SuddenPineapple** [comment]
I would make it so backspase goes back btw

**Comment by souvikinator** [comment]
Thanks for the feedback. I'll look into it.
