### ISSUE TITLE
fish shell support

### ISSUE THREAD

**Issue by ZeusThundr** [souvikinator/lsx#30]
fish: Unknown command: /home/zeus/go/bin/ls-x
~/.config/fish/functions/lsx.fish (line 15):
        $LSX
        ^
in function 'lsx'

console output when I try to run lsx
Sorry for not providing more info but just seem like a simple fish script syntax error I don't know how to write scripts in fish shell.
I don't think this issue is on my end I just think fish doesn't use $ the same way bash or zsh do?
**EDIT:** Syntax might change depending on version of fish I am on version 3.3.1-1

**Comment by souvikinator** [comment]
Hey I'm also using fish shell 3.3.1 and works fine on my end.
Can you provide me following info:
1. what does `echo $GOPATH` returns?
2. is "$GOPATH/bin" added to the path?

**Comment by ZeusThundr** [comment]
my go path is /home/zeus/.local/share/go and inside the bin directory lsx is inside there and runs as executable

**Comment by ZeusThundr** [comment]
sorry for the issue It was on my end I set environment variables in my fish config In order to keep my home directory clutter free. I changed the path inside the lsx.fish function to be my $GOPATH instead of ~/home/zeus/go/bin. changing the function to specify the environment variable might help future user's thank you for leading me in the right direction @souvikinator

**Comment by souvikinator** [comment]
Great! Thanks for using.
